### ISSUE TITLE
App verifier reports errors in unit tests

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#105]
Build steps:
cmake -G "Visual Studio 14 2015 Win64" .. -DTHREADING_ANALYSIS_MODE=ON
cmake --build . --config Debug

AppVerifier Version: 10.0 (x64)
Checks: Basics and Cuzz

Unit tests:
embb_mtapi_c_test.exe (Plugintest)
embb_mtapi_network_c_test.exe (NetworkTaskTest)
embb_base_c_test (ConditionVarTest)

See attachments:
[embb_mtapi_c_test.exe.0.dat.txt](https://github.com/siemens/embb/files/1030071/embb_mtapi_c_test.exe.0.dat.txt)
[embb_mtapi_network_c_test.exe.0.dat.txt](https://github.com/siemens/embb/files/1030087/embb_mtapi_network_c_test.exe.0.dat.txt)
[embb_base_c_test.exe.2.dat.txt](https://github.com/siemens/embb/files/1030143/embb_base_c_test.exe.2.dat.txt)

**Comment by marcus-winter** [comment]
The problem in embb_mtapi_network_c_test is a false positive. App verifier complains that an invalid socked handle is passed to recv. At this point the handle was just created and returned as pending by select. Subsequently, if the exception is ignored, the socket in question works perfectly normal. See also #37.

**Comment by marcus-winter** [comment]
The problem in embb_mtapi_c_test is a bug in mtapi where allocated objects in pools are not destroyed when the pool is destroyed.

**Comment by marcus-winter** [comment]
The problem in embb_base_c_test is a problem with statement order. The mutex held in the notification test is destroyed on thread 0 before all other threads call unlock. See https://github.com/siemens/embb/commit/c56be95a08c163cc037d002d3a3ba88b04f77f54.
