### ISSUE TITLE
Cannot build Doxygen documentation in certain cases

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#12]
Sometimes, nothing happens except for the following output when trying to build the Doxygen documentation:

cmake --build . --target doxygen
-- Running Doxygen
Built target doxygen

**Comment by marcus-winter** [comment]
This happens when cmake was run first without doxygen installed. It does not automatically redetect doxygen unless you delete the cache and rebuild. I'm going to introduce an error message so it is clear that doxgen was not found initially.

**Comment by marcus-winter** [comment]
Please review #26

**Comment by tobias-schuele** [comment]
If you use the GitHub syntax such as "Fixes #12" (https://help.github.com/articles/closing-issues-via-commit-messages/), issues are closed automatically.
