### ISSUE TITLE
Zip release files

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#13]
Currently, only a .tar.gz file is generated for releases. This is a bit cumbersome for Windows. Additionally, a .zip file would be useful.

**Comment by christian-kern** [comment]
The create_tarball script has to be adjusted, to additionally generate a zip file. Currently, a tar.gz is created this way:

```
#finally, build the tarball.
echo "--> Calling tar"
tar -czf $TARBALL_NAME -C $MYTMPDIR ${n}
```

Afterwards, Jenkins has to be adjusted, so this ".zip" artifact is kept, and can be downloaded by the user, like it was done for the tar.gz.

**Comment by christian-kern** [comment]
See https://github.com/siemens/embb/commit/74ef64d633bf1e6ecc7d6b865387ee314659a1a3

Jenkins is not set up yet as the branch is not yet merged to master.

**Comment by tobias-schuele** [comment]
Both the .tar.gz and the .zip file contain a file "myfile.properties" in the root directory which should be removed.

**Comment by marcus-winter** [comment]
Verified on Jenkins, closing.
