### ISSUE TITLE
Revise tutorial

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#19]
The tutorial needs to be revised and extended. As a first step, outline what has to be changed in which sections. This includes a description of those parts that have been added since the last version of the tutorial such as support for heterogeneous systems (algorithms, dataflow, CUDA plugin, etc.)

**Comment by marcus-winter** [comment]
Sections for heterogeneous algorithms and dataflow need to be added. There is no tutorial for the CUDA plugin. Everything else is covered albeit a bit brief.

**Comment by tobias-schuele** [comment]
Updated tutorial is available in embb19-revise_tutorial. I propose to move the section on MTAPI at the end and to start with the high-level patterns (algorithms). Changes to the text are probably necessary to maintain a consistent flow. Final review will follow once support for heterogeneous systems is integrated.
