### ISSUE TITLE
add core infrastructure initiative badge

### ISSUE THREAD

**Issue by bufferoverflow** [siemens/embb#23]
Would be cool to have a badge from https://bestpractices.coreinfrastructure.org/ see e.g. https://bestpractices.coreinfrastructure.org/projects/29

**Comment by tobias-schuele** [comment]
Initial version available here: https://bestpractices.coreinfrastructure.org/projects/654 (not yet complete)

**Comment by tobias-schuele** [comment]
Completed CII assessment.
