### ISSUE TITLE
Use mutex in spinlock for threading analysis

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#34]
Threading analysis mode allows to run tools such as Helgrind for finding data races etc. However, in case of spinlocks, the actual semantics is hidden from Helgrind as atomics are replaced by mutexes. To solve this problem, use simple mutexes inside spinlocks instead of a loop (if and only if analysis mode is enabled).

**Comment by tobias-schuele** [comment]
See existing branch embb34-mutex_spinlock_threading_analysis.

**Comment by marcus-winter** [comment]
Jenkins ran all tests successfully, closing.
