### ISSUE TITLE
embb_mtapi_c_test.exe failure

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#38]
Visual Studio 1015 Win64, AppVerify 10.0

Latest commit: https://github.com/siemens/embb/commit/1e9bb0e5d545875dbd23509535acf00574c4e503

See also attached screenshot
![embb_mtapi_c_test1](https://cloud.githubusercontent.com/assets/8639867/21217929/f5436cba-c2ae-11e6-8fe3-b7310b82fd49.png)

**Comment by marcus-winter** [comment]
Reproduced the problem. Looks like the action is being deleted before all associated tasks have finished.
