### ISSUE TITLE
Compilation problem with VS 2013 when using default constructor of dataflow network

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#42]
On Visual Studio 2013, the compiler emits an error message when omitting the number of slices in the constructor of a network:

`Error	2	error C2664: 'embb::dataflow::Network::Source<ArrayWrapper<float,1,6>,embb::base::internal::Nil,embb::base::internal::Nil,embb::base::internal::Nil,embb::base::internal::Nil>::Source(const embb::dataflow::Network::Source<ArrayWrapper<float,1,6>,embb::base::internal::Nil,embb::base::internal::Nil,embb::base::internal::Nil,embb::base::internal::Nil> &)' : cannot convert argument 1 from 'MyNetwork (__cdecl *)(void)' to 'embb::dataflow::Network &'
`
The same program compiles when the number of slices is specified.

**Comment by marcus-winter** [comment]
This error occurs when `embb::dataflow::Network network();` is used instead of `embb::dataflow::Network network;` which compiles just fine.
