### ISSUE TITLE
Tutorial application

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#55]
Review and revise video processing tutorial if necessary. Describe the application in the tutorial and include the source code in the examples directory.

**Comment by marcus-winter** [comment]
The application contains several binary libraries. We need to discuss what to do with them.

**Comment by tobias-schuele** [comment]
Keep ffmpeg but do not include binaries. Include reference where to obtain development packages (at least for Windows, Linux users can use libraries included in distribution).

Besides stream processing, also explain usage of parallel algorithms for filter(s) and as an add-on heterogeneous systems (OpenCL). Ideally, pipeline should have one stage (process) for each processing step.

**Comment by tobias-schuele** [comment]
Add comments in CMakeLists.txt explaining the basics and things to be adapted such as paths. Use "MYPATH" or something similar instead of actual paths and comment out.

**Comment by tobias-schuele** [comment]
README: Prerequisites, installation, building, running (but not details about implementation).
Tutorial: Explanation of the algorithms, used patterns, code snippets, etc.
