### ISSUE TITLE
Integration of EMBB into own projects via CMake

### ISSUE THREAD

**Issue by tobias-schuele** [siemens/embb#58]
As a user, I do not want to set the paths, libs etc. manually that are required to use EMBB. CMake allows to easily integrate other projects into own applications. Provide suitable CMake files that enable such integration. See

- https://github.com/siemens/embb/commit/6c998fa8de02793fb4f4b776e005bfd8f9e88193
- https://github.com/siemens/embb/commit/7cd8f0ebc160026dc6e9fdf5386f382b1c890faf

**Comment by marcus-winter** [comment]
So far we only have a description for that on the website. Should I put a section into the readme as well?

**Comment by tobias-schuele** [comment]
Where on the web site? Should be definitely part of the README, I propose after the section "Using C".

**Comment by marcus-winter** [comment]
https://embb.io/get_started.html sections "Creating and Running an Application"

**Comment by marcus-winter** [comment]
Added a section to the README (see https://github.com/siemens/embb/commit/ee2c58151b85f29ee8fcc126a23a38b90df3c1e8). Shall I change the website, too?

**Comment by tobias-schuele** [comment]
I will add a note on the website.
